### ISSUE TITLE
Add to postcss-utilities

### ISSUE THREAD

**Issue by ai** [m18ru/postcss-text-remove-gap#1]
What do you think about adding this plugin to this pack? https://github.com/ismamz/postcss-utilities

**Comment by Avol-V** [comment]
As I can see, this pack is a set of mixins, but my plugin is not a mixin. It uses per-project basis settings and maintainable fonts storage, and also works in CSS block space, using other properties in the same block – not like pure function, that mixins is.

Or you have some arguments for this?

**Comment by ai** [comment]
Ouh, yeap. I missed your plugin options.
