### ISSUE TITLE
If you build it, they will come

### ISSUE THREAD

**Issue by jednano** [m18ru/postcss-text-remove-gap#2]
What I find very interesting is that I specifically built [`postcss-font-helpers`](https://github.com/jedmao/postcss-font-helpers) so that someone would build this very PostCSS plugin and that's exactly what happened!

Thanks for the plugin!

**Comment by Avol-V** [comment]
I will reply to your issues later, sorry — just don't have enough time for now. And I'll create a new version with respect to your recommendations :)
